"""empty message

Revision ID: a4909ffd6851
Revises: 57509fbef67b
Create Date: 2020-03-22 18:38:49.717332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4909ffd6851'
down_revision = '57509fbef67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('total_confirmed', sa.Integer(), nullable=True),
    sa.Column('total_deaths', sa.Integer(), nullable=True),
    sa.Column('total_recovered', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('new_confirmed', sa.Integer(), nullable=True),
    sa.Column('new_deaths', sa.Integer(), nullable=True),
    sa.Column('new_recovered', sa.Integer(), nullable=True),
    sa.Column('death_rate', sa.Float(), nullable=True),
    sa.Column('increase_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_report')
    # ### end Alembic commands ###
