"""empty message

Revision ID: abf4375a736c
Revises: 0bf9607cc4c9
Create Date: 2020-03-27 16:14:36.673258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf4375a736c'
down_revision = '0bf9607cc4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_report')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('death_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('increase_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('new_confirmed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_deaths', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_recovered', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_active', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_confirmed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_deaths', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_recovered', sa.Integer(), nullable=True))
        batch_op.drop_column('recovered')
        batch_op.drop_column('confirmed')
        batch_op.drop_column('province')
        batch_op.drop_column('deaths')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deaths', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('confirmed', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('recovered', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_recovered')
        batch_op.drop_column('total_deaths')
        batch_op.drop_column('total_confirmed')
        batch_op.drop_column('total_active')
        batch_op.drop_column('new_recovered')
        batch_op.drop_column('new_deaths')
        batch_op.drop_column('new_confirmed')
        batch_op.drop_column('increase_rate')
        batch_op.drop_column('death_rate')

    op.create_table('latest_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('report_date', sa.DATE(), nullable=True),
    sa.Column('total_confirmed', sa.INTEGER(), nullable=True),
    sa.Column('total_deaths', sa.INTEGER(), nullable=True),
    sa.Column('total_recovered', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.INTEGER(), nullable=True),
    sa.Column('new_confirmed', sa.INTEGER(), nullable=True),
    sa.Column('new_deaths', sa.INTEGER(), nullable=True),
    sa.Column('new_recovered', sa.INTEGER(), nullable=True),
    sa.Column('death_rate', sa.FLOAT(), nullable=True),
    sa.Column('increase_rate', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
